### ISSUE TITLE
Very slow Single Sign Out ~ 1 min

### ISSUE THREAD

**Issue by fsh1** [thinktecture/Thinktecture.IdentityServer.v3.WsFederation#11]
I'm using an IdentityServer OWIN configuration with an WS-Federation plugin configured.
The server's URL : https://root.openid.md/
The RP's URL: 
1) https://client.openid.md/
2) http://bistro.md/
3) http://lunch.md/

The RP's are configured exactly as (MVC OWIN WS-Federation example).

The Single Sign In works excellent. But when it comes to SSO, there is a significant delay, about ~ 1 min.

Scenario from Trace.log file:
1) I'm SignIn to all RP's (one of them requires Login and Password, others are being automatically signed in)
2) I'm performing an LogOut from https://client.openid.md/
3) The Signout Page from http://root.openid.md/ appears after which I click Sign Out.
4) Other RP's are still signed in. I'm constantly refreshing any page (including with [Authorize] attr.) of any remaining RP's, and approximatively after 1 min, they are being signed out.

The Trace.log file is below:
https://drive.google.com/file/d/0B_QAgAHaOvE2N29yaFZ0Q1pDdEU/view?usp=sharing

**Comment by brockallen** [comment]
IIRC, the Katana WS-Fed middleware doesn't support signoutcleanup. @leastprivilege do you recall for certain?

**Comment by leastprivilege** [comment]
i think that is true.

**Comment by brockallen** [comment]
You can add it yourself, but unfortunately, it's a manual addition in each RP.

**Comment by fsh1** [comment]
Thank you for fast reply. I'll learn more about it and try to find a solution. If there will be any updates regards the signoutcleanup please keep in touch. Cheers

**Comment by brockallen** [comment]
They say it won't be fixed until vNext (meaning the new ASP.NET 5 runtime).

**Comment by fsh1** [comment]
Noticed, thank you.
