### ISSUE TITLE
Performing a request with iframe from HTTPS to HTTP is being blocked.

### ISSUE THREAD

**Issue by fsh1** [thinktecture/Thinktecture.IdentityServer.v3.WsFederation#13]
The procedure of signing out of all RP's is achieved via performing a HTTP GET request through an iframe element:

``` "<iframe style=\"visibility: hidden; width: 1px; height: 1px\" src=\"{0}?wa=wsignoutcleanup1.0\"></iframe>"; ```

There is an issue with this implementation if using __HTTPS protocol on Idsrv__ and __HTTP on RP's__:
> Mixed Content: The page at 'https://auth.domain.com/' was loaded over HTTPS, but requested an insecure resource 'http://client.com/'. This request has been blocked; the content must be served over HTTPS.

Explaination: https://developer.mozilla.org/en-US/docs/Security/MixedContent

*Question*: Was the iframe an intentional choice for preventing Mixed HTTPx requests.
Why not using an image instead ?
```<img style=\"visibility: hidden; width: 1px; height: 1px\" src=\"{0}?wa=wsignoutcleanup1.0\">```

**Comment by brockallen** [comment]
Well, that error is coming from the browser and not from any of our code. Having said that, it's a legit error -- you should not be running the RP (or the STS) over HTTP; you should always be using HTTPS. I can sort of understand in development not using SSL, but then you won't really be developing and testing how you will eventually deploy. Also, it's not that hard to get SSL working in VS and IIS Express.

**Comment by fsh1** [comment]
@brockallen Yes its not a problem to setup an SSL while development but why should the RP strictly use HTTPS? Isn't this a limitation after all?

**Comment by brockallen** [comment]
The RP needs SSL because tokens are being sent to it. Do you want those tokens sent over the plaintext shared network? I don't. Also, what about the cookie it issues to log the user in? What about the content it's showing to the user? If you're not using SSL then all of that is basically leaked onto the shared plaintext network.

**Comment by fsh1** [comment]
@brockallen Thank you very much for explaination.
