### ISSUE TITLE
Make SignInValidator to use WS-federation parameters provided by client

### ISSUE THREAD

**Issue by janih78** [thinktecture/Thinktecture.IdentityServer.v3.WsFederation#9]
It would be helpful if we could use e.g. Wreply provided by a client instead of getting it from relaying parties configuration. There are cases where the same application is installed into multiple servers and thus the reply address might be different for each of them (while other options remain the same). By using client provided reply address, we need to configure only one relaying party for all instances of the application.

**Comment by leastprivilege** [comment]
Are you saying that you want to register all possible wreply addresses with idsrv - and the wreply param can choose from one of those?

**Comment by janih78** [comment]
I mean if we have, let's say, two installations of the same application on different IIS servers that are

(A) http://servername1:10000
(B) http://servername2:10000

and we want to be able to authenticate both of those using IdentityServer (and WS-Federation) installed somewhere.

As far as I'm understood, we have to configure both applications (A and B) in IdentityServer using RelayingParties.cs. So RelayingParties.cs will contain two relaying parties with identical values except Realm and ReplyUrl.

                new RelyingParty
                {
                    Realm = "urn:myAppOnServer1",
                    Enabled = true,
                    ReplyUrl = "http://servername1:10000/",
                    ...
                },
                new RelyingParty
                {
                    Realm = "urn:myAppOnServer2",
                    Enabled = true,
                    ReplyUrl = "http://servername2:10000/",
                    ...
                }

So, what I'm suggesting is that clients could provide Wreply parameter because it's the only value that differs. With this change, RelayingParties.cs might look like this

                new RelyingParty
                {
                    Realm = "urn:myApp",
                    Enabled = true,
                    // ReplyUrl is provided by the client
                    ...
                }

There might be another solutions for this issue, but the common goal is to avoid copy-pasting those relaying parties in RelayingParties.cs when the ReplyUrl is the only difference.

**Comment by leastprivilege** [comment]
Allowing the client to supply the wreply is a major security problem. You only want to deliver your tokens to fixed, pre-registered locations.

**Comment by janih78** [comment]
I agree that.

Is there any other way to solve this? Maybe to register all reply url's and then use wreply param to choose from one of those - as you suggested?

**Comment by leastprivilege** [comment]
Well - this is still not really an option because of the audience in the resulting token (which is the same as the realm name).

e.g. app1 and app2 use the the same realm in idsrv - but each have their own reply URL. 

now every app must be configured with the same audience - and app1 can now use the received token to sign into app2.

**Comment by janih78** [comment]
Haven't think about that, but sounds a good reason not to implement that kind of functionality. Anyway, thanks for replying fast. I'll close this.
